# Generated by Django 4.2.13 on 2026-06-23 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('event_type', models.CharField(choices=[('connection', 'Conexión'), ('auth_failure', 'Login fallido'), ('auth_success', 'Login correcto'), ('other', 'Otro')], default='other', max_length=20)),
                ('source_ip', models.GenericIPAddressField(verbose_name='IP de origen')),
                ('dest_port', models.PositiveIntegerField(blank=True, null=True, verbose_name='Puerto destino')),
                ('username', models.CharField(blank=True, max_length=150)),
                ('detail', models.CharField(blank=True, max_length=255)),
                ('sensor', models.CharField(blank=True, max_length=100, verbose_name='Sensor que reportó')),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('is_alert', models.BooleanField(default=False, verbose_name='Disparó una regla')),
                ('rule', models.CharField(blank=True, max_length=40, verbose_name='Regla disparada')),
                ('triggered_incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='incidents.incident', verbose_name='Incidente generado')),
            ],
            options={
                'verbose_name': 'Evento de seguridad',
                'verbose_name_plural': 'Eventos de seguridad',
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['source_ip', 'received_at'], name='ingest_secu_source__5155a9_idx')],
            },
        ),
    ]
