# Generated by Django 4.2.13 on 2026-06-28 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
        ('ingest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_ip', models.GenericIPAddressField(unique=True, verbose_name='IP bloqueada')),
                ('rule', models.CharField(max_length=40, verbose_name='Regla que la disparó')),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('active', models.BooleanField(default=True, verbose_name='Bloqueo activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('released_at', models.DateTimeField(blank=True, null=True, verbose_name='Liberada el')),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocked_ips', to='incidents.incident', verbose_name='Incidente que la originó')),
            ],
            options={
                'verbose_name': 'IP bloqueada',
                'verbose_name_plural': 'IPs bloqueadas',
                'ordering': ['-created_at'],
            },
        ),
    ]
