# Generated by Django 4.2.13 on 2026-06-29 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0002_blockedip'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockedip',
            name='alerted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Notificado el'),
        ),
    ]
