# Generated by Django 4.2.13 on 2026-06-29 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0003_blockedip_alerted_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertThrottle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('window_started_at', models.DateTimeField(blank=True, null=True)),
                ('suppressed', models.PositiveIntegerField(default=0, verbose_name='Incidentes en cola')),
                ('suppressed_titles', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Estado de notificaciones',
                'verbose_name_plural': 'Estado de notificaciones',
            },
        ),
    ]
