# Generated by Django 4.2.13 on 2026-06-08 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('steps', models.JSONField(default=list, verbose_name='Pasos del plan')),
                ('is_customized', models.BooleanField(default=False, verbose_name='Editado por analista')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('incident', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='action_plan', to='incidents.incident')),
            ],
            options={
                'verbose_name': 'Plan de Acción',
                'verbose_name_plural': 'Planes de Acción',
            },
        ),
    ]
